document.getElementById("p1").innerHTML = "Hello JavaScript";
document.getElementById('p1').style.color='red';
document.getElementById("p2").innerHTML = "This is the javascript";
document.getElementById('p2').style.color='orange';
document.getElementById("p3").innerHTML = "This is another  line of javascript";
document.getElementById('p3').style.color='blue';
document.getElementById('intro').style.color='white';
document.getElementById('intro').style.fontSize='35px';
document.body.style.backgroundColor  = "black";